# promise

## API

Promise 实例具有三种状态

- pending 异步操作未完成
- fulfilled 兑现，异步操作成功
- rejected 拒绝，异步操作失败

这三种状态的变化途径只有两种

- 从 pending 到 fulfilled
- 从 pending 到 rejected

函数：

- `Promise.then`：最多接受两个参数，用于 Promise 在 fulfilled 和 rejected 时的回调函数，返回一个等效的 Promise 对象。
- `Promise.resolve`：使用给定 value 创建一个 resolved 的 promise。
- `Promise.reject`：使用给定 error 创建一个 rejected 的 promise。
- `Promise.all`：静态方法接受一个 Promise 可迭代对象（数组为可迭代对象），并返回一个 Promise。当所有输入的 Promise 都为 fulfilled 时，返回的 Promise 也将为 fulfilled；当任意一个 promise 被 reject，返回的 promise 就为 rejected，并且带有这个 error，所有其他 promise 的结果都会被忽略。
- `Promise.allSettled`：返回保留所有 promise 的执行结果（settled 包含 fulfilled 和 rejected）的 promise。对于 `Promise.all` 如果任意的 promise reject，则其他 promise 的结果都会被忽略。
- `Promise.race`：与 `Promise.all` 类似，但只等待第一个 settled 的 promise 并获取其结果（或 error）。
- `Promise.any`与 `Promise.race` 类似，区别在于 `Promise.any` 只等待第一个 fulfilled 的 promise，并将这个 fulfilled 的 promise 返回。

## 问题

### then 链式调用
`then` 方法返回一个新的 Promise 实例，因此可以链式调用。后一个 `then` 方法接收前一个 `then` 方法的返回值作为参数，并且只会调用 resolve 函数。也就是无论前一个 promise 的状态如何，then 调用后返回的 promise 均为 fulfilled。
``` js
var promise = new Promise(function (resolve, reject) {
  reject("ok");
});
promise
  .then(
    function (value) {
      console.log("resolve", value);
      return value;
    },
    function (value) {
      console.log("reject", value);
      return value;
    }
  )
  .then(function (value) {
    console.log("second", value);
  })
  .catch(() => console.log("promise catch err"));

// 控制台输出
// reject ok
// second ok
```

有点 generator 的样子了。

### Promise 会吃掉错误

在浏览器中执行以下代码：

```js
const doAsyncThing = function () {
  return new Promise(function (resolve, reject) {
    // 下面一行会报错，因为 x 没有声明
    throw new Error("test error");
  });
};

doAsyncThing()

setTimeout(() => {
  console.log(123);
}, 2000);
// Uncaught (in promise) Error: test error
// 123
```

上面代码中，`someAsyncThing()`函数产生的 Promise 对象，内部有语法错误，浏览器会打印出错误提示`ReferenceError: x is not defined`，但是不会退出进程、终止脚本执行，2 秒之后还是会输出`123`。

阮一峰的 es6 书籍中说：

> 跟传统的`try/catch`代码块不同的是，如果没有使用`catch()`方法指定错误处理的回调函数，Promise 对象抛出的错误不会传递到外层代码，即不会有任何反应。
> 

*抛出的错误不会传递到外层代码* 这句话换成人话就是：设置 `window.onerror` 捕获 `error` ，是捕获不到 promise 内部抛出的错误，看以下代码，`onerror` 里的打印并未执行（即捕获不到 promise 内部 throw 的 `error`：

```jsx
window.onerror = function () {   // 我们添加了 window 的 onerror 处理函数
    console.log('window err')
} 

promise = new Promise(function(resolve, reject) {
    throw new Error('test');
});
promise.then(function(value) { console.log(value) })   

// 控制台输出:
// Uncaught (in promise) Error: test
```

如果加了 catch，是能捕获到内部的错误

```jsx
window.onerror = function () {
    console.log('window err')
} 

var promise = new Promise(function(resolve, reject) {
    throw new Error('test');
});

promise
    .then(function(value) { console.log(value) })
    .catch((err) => console.log('promise catch err'))

// 控制台输出:
// promise catch err
```

有些博客说吃掉错误是指不影响全局代码的执行，这是误解，**实际应是 promise 外部捕获不到内部抛出的错误。**

在浏览器中，确实不会影响全局代码的执行。
但是在 nodeJS 中，会影响全局代码的执行，直接 exit 0 了，必须设置 catch，才会继续执行。

```jsx
const doAsyncThing = function () {
  return new Promise(function (resolve, reject) {
    // 下面一行会报错，因为 x 没有声明
    throw new Error("test error");
  });
};

doAsyncThing();

setTimeout(() => {
  console.log(123);
}, 2000);

// 控制台输出:
// Error: test error
```

链式调用 promise 时，写上 catch 是一个好习惯。

## 手写 promise

```jsx
const PENDING = "PENDING";
const FULFILLED = "FULFILLED";
const REJECTED = "REJECTED";

class MyPromsie {
  constructor(executor) {
    this.status = PENDING;
    this.value = undefined;
    this.reason = undefined;
    this.onResolvedCallbacks = [];
    this.onRejectedCallbacks = [];

    let resolve = (value) => {
      if (this.status == PENDING) {
        this.status = FULFILLED;
        this.value = value;
        this.onResolvedCallbacks.forEach((fn) => fn());
      }
    };

    let reject = (reason) => {
      if (this.status == PENDING) {
        this.status = REJECTED;
        this.reason = reason;
        this.onRejectedCallbacks.forEach((fn) => fn());
      }
    };

    try {
      executor(resolve, reject);
    } catch (e) {
      reject(error);
    }
  }

  then(onFullfilled, onRejected) {
    if (this.status == FULFILLED) {
      onFullfilled(this.value);
    }

    if (this.status == REJECTED) {
      onRejected(this.reason);
    }

    if (this.status === PENDING) {
      // 如果 promise 的状态是 pending，需要将 onFulfilled 和 onRejected 函数存放起来，等待状态确定后，再依次将对应的函数执行
      this.onResolvedCallbacks.push(() => {
        onFullfilled(this.value);
      });

      // 如果 promise 的状态是 pending，需要将 onFulfilled 和 onRejected 函数存放起来，等待状态确定后，再依次将对应的函数执行
      this.onRejectedCallbacks.push(() => {
        onRejected(this.reason);
      });
    }
  }
}

let p1 = new MyPromsie((res) => {
  setTimeout(() => {
    res("ok");
  }, 1000);
});
p1.then((res) => {
  console.log("then", res);
});
```

## 应用场景

1. 在访问接口的时候，需要有过渡动画，实现一个需求，如果接口在半秒内响应完毕，只显示半秒的过渡动画，若超过，则等到接口响应完毕再关闭动画。

```jsx
function API() {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve();
    }, 5000);
  });
}

let loadTime = () => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve();
    }, 500);
  });
};

function wrapFun(request) {
  return Promise.allSettled([loadTime(), request()]);
}

wrapFun(API).then(() => {
  console.log("ok");
});
```

2. 实现最多 5 个并行请求。

```jsx
// 在并行请求多张图片，由于 Chrome 浏览器的 network 模块最大能够同时发起 6 个请求
// 如果超过可能会导致浏览器网络过载，从而影响页面加载性能
// 例如在页面同时发起 20 个请求，发起请求就会占用内存，即使实际未被 network 模块处理。
// 设计实现分批发送请求的功能，假设最多同时发起 6 个请求，需要处理的请求有很多个。
let i = 0;
let arr = new Array(18).fill("url");
limitLoad(arr, 6);

function API(url) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      // 假设 20% 可能性请求失败
      if (Math.random() + 0.8 > 1) {
        resolve("ok");
      } else {
        reject("error");
      }
    }, 1000);
  });
}

function limitLoad(requests, limit) {
  const promises = requests.slice(0, limit).map((url, index) => {
    return API(url).then(
      () => index,
      () => index
    );
  });

  return requests
    .reduce((pre, url, index) => {
      if (index < limit) {
        return pre;
      }
      return pre
        .then(() => Promise.race(promises))
        .then((idx) => {
          console.log(
            `第${idx}个位置的请求结束，将第${index}个接口放入,共${requests.length}个请求`
          );
          promises[idx] = API(url).then(
            () => index,
            () => index
          );
        })
        .catch((err) => console.error(err));
    }, Promise.resolve())
    .then(() => Promise.allSettled(promises))
    .then((res) => console.log(res));
}
// 还可以再优化逻辑，将结果都记录
```

## 参考资料
[Promise API](https://zh.javascript.info/promise-api)